<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE coches [
    <!ELEMENT coches (coche+)>
    <!ELEMENT coche (marca,modelo,puertas,color,precio)>
    <!ATTLIST coche matricula CDATA #REQUIRED>
    <!ELEMENT marca (#PCDATA)>
    <!ELEMENT modelo (#PCDATA)>
    <!ELEMENT puertas (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    <!ELEMENT precio (#PCDATA)>
    <!ATTLIST precio venta CDATA #REQUIRED>
]>
<coches>
    <coche matricula="1234MMM">
        <marca>Seat</marca>
        <modelo>Leon</modelo>
        <puertas>5</puertas>
        <color>Rojo</color>
        <precio venta="nuevo">20000</precio>
    </coche>
    <coche matricula="4321LLL">
        <marca>Kia</marca>
        <modelo>Ceed</modelo>
        <puertas>3</puertas>
        <color>Negro</color>
        <precio venta="ocasion">18000</precio>
    </coche>
</coches>