<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE colegio [
    <!ELEMENT colegio (alumnos,profes)>
    <!ELEMENT alumnos (alumno+)>
    <!ELEMENT alumno (nombre,apellido,matricula,activo)>
    <!ATTLIST alumno expediente CDATA #REQUIRED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT matricula (#PCDATA)>
    <!ELEMENT activo EMPTY>
    <!ELEMENT profes (profe+)>
    <!ELEMENT profe (nombre,curso,foto)>
    <!ELEMENT curso (#PCDATA)>
    <!ELEMENT foto (#PCDATA)>
]>
<colegio>
    <alumnos>
        <alumno expediente="AA01">
            <nombre>Marc</nombre>
            <apellido>Venteo</apellido>
            <matricula>ASIX</matricula>
            <activo />
        </alumno>
        <alumno expediente="AA02">
            <nombre>Ana</nombre>
            <apellido>Venteo</apellido>
            <matricula>DAW</matricula>
            <activo />
        </alumno>
    </alumnos>
    <profes>
        <profe>
            <nombre>Juan</nombre>
            <curso>DAW</curso>
            <foto>Juan.jpg</foto>
        </profe>
    </profes>
</colegio>