<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reyes_espanoles [
 <!ELEMENT reyes_espanoles (rey*, reina*)>
 <!ELEMENT rey (nombre, padre, madre)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT padre (#PCDATA)>
 <!ELEMENT madre (#PCDATA)>
 <!ELEMENT reina (nombre, padre, madre)>
]>
<reyes_espanoles>
    <rey>
        <nombre>Felipe III</nombre>
        <padre>Felipe II</padre>
        <madre>Ana de Austria</madre>
    </rey>
    <rey>
        <nombre>Carlos I</nombre>
        <padre>Felipe el Hermoso</padre>
        <madre>Juan la Loca</madre>
    </rey>
    <reina>
        <nombre>Juana la Loca</nombre>
        <padre>Fernando el Católico</padre>
        <madre>Isabel la Católica</madre>
    </reina>
</reyes_espanoles>